# Generated by Django 3.1.7 on 2021-03-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210307_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='origianl_bag',
            new_name='original_bag',
        ),
    ]
